
get:
	scp -p -o proxycommand="ssh gate.ebi.ac.uk proxy %h" mahogny@ebi-login.ebi.ac.uk:/homes/mahogny/common/data/liora_20180307/counttable_ht.csv ./
#	scp -p -o proxycommand="ssh gate.ebi.ac.uk proxy %h" mahogny@ebi-login.ebi.ac.uk:/homes/mahogny/common/data/liora_20180320_foxp3/counttable.csv ./

put:
